name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # AWS 리전으로 교체하세요.

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 3.39.12.144 # EC2 인스턴스의 공용 IP 주소로 교체하세요.
          username: ubuntu # EC2 인스턴스의 사용자 이름으로 교체하세요.
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
